In [1]:
import plotly.offline as offline
import plotly.graph_objs as go
offline.init_notebook_mode()
import numpy as np
import pandas as pd

Output hidden; open in https://colab.research.google.com to view.

In [2]:
x1 = [0, 1, 2, 3, 4, 5, 6, 7, 8]
y1 = [0, 1, 2, 3, 4, 5, 6, 7, 8]
z1 = [0, 1, 2, 3, 4, 5, 6, 7, 8]

x2 = [0, 1, 2, 3, 4, 5, 6, 7, 8]
y2 = [0, 1, 2, 3, 4, 5, 6, 7, 8]
z2 = [1, 0, 3, 2, 5, 4, 7, 6, 8]

In [ ]:
# https://plot.ly/python/3d-axes/
trace1 = go.Scatter3d(x=x1,y=y1,z=z1, name = 'train')
trace2 = go.Scatter3d(x=x2,y=y2,z=z2, name = 'Cross validation')
data = [trace1, trace2]

layout = go.Layout(scene = dict(
        xaxis = dict(title='n_estimators'),
        yaxis = dict(title='max_depth'),
        zaxis = dict(title='AUC'),))

fig = go.Figure(data=data, layout=layout)
offline.iplot(fig, filename='3d-scatter-colorscale')

In [6]:
d={"name":["rahul","priyanka","mohit","monu"],
   "roll no":[146,789,224,514],
   "age":[28,25,28,30]}
data=pd.DataFrame(d)
print(data)

       name  roll no  age
0     rahul      146   28
1  priyanka      789   25
2     mohit      224   28
3      monu      514   30

In [7]:
data["name"]

0       rahul
1    priyanka
2       mohit
3        monu
Name: name, dtype: object

In [34]:
for x in range(len(data["name"])):

  print(data["name"].values[x])
  print(data.loc[x])

rahul
name       rahul
roll no      146
age           28
Name: 0, dtype: object
priyanka
name       priyanka
roll no         789
age              25
Name: 1, dtype: object
mohit
name       mohit
roll no      224
age           28
Name: 2, dtype: object
monu
name       monu
roll no     514
age          30
Name: 3, dtype: object